# -*- coding: utf-8 -*-
"""Abhiram_EDA on salesdataset.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1azhOBjcXtBS1h5B_VwP10H65IDi9IDc3
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
x=pd.read_csv("sales.csv")

x.columns=['Year','Product','line','Product.1','type','Product.2','Order','method','type.1','Retailer','country','Revenue']

x.loc[len[x]]=

x.head(5)

x['country'].unique()

x[x['country']=='States'].head()

x.shape

x.describe()

x.info()

x.isnull()

x.isnull().sum()

x['country'][3]=None

x.isnull()

y = x[['Revenue']].mean()

x.isnull().sum()

from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()

x['Year'] = labelencoder.fit_transform(x['Year'])

sns.countplot(x['Revenue'].values)
plt.xlabel('Revenue')
plt.ylabel('country')
plt.show()

fig = plt.figure()
plt.boxplot([x[x['Year']==0]['Revenue'], x[x['Year']==1]['Revenue'],x[x['Year']==2]['Revenue']])
plt.show()

fig = plt.figure()
plt.scatter(x = [i for i in range(len(x[x['Year']==0]['Revenue']))], y = x[x['Year']==0]['Revenue'])
plt.ylabel('Revenue for class 0')

from sklearn.preprocessing import StandardScaler
Stdscaler = StandardScaler()
m= x[['Year','Revenue']]
M = Stdscaler.fit_transform(m)

M[:5]

from sklearn import preprocessing
X = x[['Year','Revenue']]
y = preprocessing.normalize(X)

y[:5]

"""We can use Random forest regression algorithm for our data set as it reduces a lot of strain on the machine learning model during pre processing and cleansing the data.The data attributes chosen for the machine learning model would have major impact on the efficiency of the model so this algorithm enhances accuracy and understanding of the model."""